server {
    listen 8080;  # Cloud Run default port
    server_name _;

    gzip on;  # Enable gzip compression

    location / {
        proxy_pass http://127.0.0.1:8888;  # Forward requests to your app on port 8888
    }
}
